//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CroustiPizz.Mobile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CroustiPizz.Mobile.Resources.AppResources.fr", typeof(AppResources_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter au panier.
        /// </summary>
        internal static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout de .
        /// </summary>
        internal static string AlertAddingToCart {
            get {
                return ResourceManager.GetString("AlertAddingToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème d&apos;accès à votre panier .
        /// </summary>
        internal static string AlertCartAccessError {
            get {
                return ResourceManager.GetString("AlertCartAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le panier est vide.
        /// </summary>
        internal static string AlertEmptyCart {
            get {
                return ResourceManager.GetString("AlertEmptyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur dans le formulaire .
        /// </summary>
        internal static string AlertFormError {
            get {
                return ResourceManager.GetString("AlertFormError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur de login et ou mot de passe.
        /// </summary>
        internal static string AlertLoginOrPasswordError {
            get {
                return ResourceManager.GetString("AlertLoginOrPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur dans les nouveaux champs entrés.
        /// </summary>
        internal static string AlertNewlyFilledEntriesError {
            get {
                return ResourceManager.GetString("AlertNewlyFilledEntriesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème d&apos;accès à vos commandes .
        /// </summary>
        internal static string AlertOrdersAccessError {
            get {
                return ResourceManager.GetString("AlertOrdersAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur mot de passe .
        /// </summary>
        internal static string AlertPasswordAndProfileErrorPart1 {
            get {
                return ResourceManager.GetString("AlertPasswordAndProfileErrorPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  et erreur sauvegarde données .
        /// </summary>
        internal static string AlertPasswordAndProfileErrorPart2 {
            get {
                return ResourceManager.GetString("AlertPasswordAndProfileErrorPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les deux mots de passe ne sont pas identiques.
        /// </summary>
        internal static string AlertPasswordMismatch {
            get {
                return ResourceManager.GetString("AlertPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe changé mais erreur sauvegarde données .
        /// </summary>
        internal static string AlertPasswordUpdatedButProfileError {
            get {
                return ResourceManager.GetString("AlertPasswordUpdatedButProfileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème d&apos;accès aux pizzerias .
        /// </summary>
        internal static string AlertPizzaShopAccessError {
            get {
                return ResourceManager.GetString("AlertPizzaShopAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur dans la commande .
        /// </summary>
        internal static string AlertPlacingOrderError {
            get {
                return ResourceManager.GetString("AlertPlacingOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commande passée avec succès.
        /// </summary>
        internal static string AlertPlacingOrderSuccess {
            get {
                return ResourceManager.GetString("AlertPlacingOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données et mot de passe sauvegardés.
        /// </summary>
        internal static string AlertProfileAndPasswordUpdateSuccess {
            get {
                return ResourceManager.GetString("AlertProfileAndPasswordUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données sauvegardées.
        /// </summary>
        internal static string AlertProfileUpdateSuccess {
            get {
                return ResourceManager.GetString("AlertProfileUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données changées mais erreur mot de passe .
        /// </summary>
        internal static string AlertProfileUpdateSuccessButPasswordError {
            get {
                return ResourceManager.GetString("AlertProfileUpdateSuccessButPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe actuel.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer mon prénom.
        /// </summary>
        internal static string EditFirstName {
            get {
                return ResourceManager.GetString("EditFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer mon nom.
        /// </summary>
        internal static string EditLastName {
            get {
                return ResourceManager.GetString("EditLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer mon adresse mail.
        /// </summary>
        internal static string EditMailAddress {
            get {
                return ResourceManager.GetString("EditMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer mon mot de passe.
        /// </summary>
        internal static string EditPassword {
            get {
                return ResourceManager.GetString("EditPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer mon numéro de téléphone.
        /// </summary>
        internal static string EditPhoneNumber {
            get {
                return ResourceManager.GetString("EditPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vider.
        /// </summary>
        internal static string EmptyCart {
            get {
                return ResourceManager.GetString("EmptyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOIR.
        /// </summary>
        internal static string EnterShop {
            get {
                return ResourceManager.GetString("EnterShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J&apos;ai oublié mon mot de passe.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identité.
        /// </summary>
        internal static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste.
        /// </summary>
        internal static string ListTab {
            get {
                return ResourceManager.GetString("ListTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse e-mail.
        /// </summary>
        internal static string MailAddress {
            get {
                return ResourceManager.GetString("MailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte.
        /// </summary>
        internal static string MapTab {
            get {
                return ResourceManager.GetString("MapTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon panier.
        /// </summary>
        internal static string MyCart {
            get {
                return ResourceManager.GetString("MyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau mot de passe.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes anciennes commandes.
        /// </summary>
        internal static string OrdersPage {
            get {
                return ResourceManager.GetString("OrdersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commandes.
        /// </summary>
        internal static string OrdersTab {
            get {
                return ResourceManager.GetString("OrdersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer le mot de passe.
        /// </summary>
        internal static string PasswordConfirmation {
            get {
                return ResourceManager.GetString("PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de téléphone.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizzerias.
        /// </summary>
        internal static string PizzaListPage {
            get {
                return ResourceManager.GetString("PizzaListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander.
        /// </summary>
        internal static string PlaceOrder {
            get {
                return ResourceManager.GetString("PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon profil.
        /// </summary>
        internal static string ProfilePage {
            get {
                return ResourceManager.GetString("ProfilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string ProfileTab {
            get {
                return ResourceManager.GetString("ProfileTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total (TTC).
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
    }
}
